appName: python-app
appReplicas: 3
containerName: python-app-container
containerPort: 8000
appImage: gcr.io/iti-project-348511/front-app  
containerEnvVars:
- name: ENVIRONMENT
  value: "DEV"
- name: HOST
  value: "localhost"
- name: PORT
  value: "8000"
- name: REDIS_HOST
  value: backend-service.default.svc.cluster.local       # Backend service IP
- name: REDIS_PORT
  value: "6379"
- name: REDIS_DB
  value: "0"   

serviceType: NodePort
servicePort: 8000
nodePort: 30035
